import './jquery'

import 'admin-lte/bower_components/jquery/dist/jquery'
import 'admin-lte/bower_components/jquery-ui/jquery-ui'
import 'admin-lte/bower_components/fastclick/lib/fastclick'
import 'admin-lte/bower_components/jquery-slimscroll/jquery.slimscroll'
import 'admin-lte/bower_components/bootstrap/dist/js/bootstrap'
import 'admin-lte/bower_components/jquery-sparkline/dist/jquery.sparkline'
import 'admin-lte/dist/js/adminlte'

import 'font-awesome/css/font-awesome.css'
import 'ionicons/dist/css/ionicons.css'
import 'admin-lte/bower_components/bootstrap/dist/css/bootstrap.min.css'
import 'admin-lte/dist/css/AdminLTE.css'
import 'admin-lte/dist/css/skins/_all-skins.css'
import 'admin-lte/plugins/iCheck/flat/blue.css'
import 'admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'